// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using beanstalk_net.DataAccess;

namespace beanstalk_net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220102071324_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("beanstalk_net.DataAccess.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Finish YouTube video",
                            CreatedOn = new DateTime(2022, 1, 2, 7, 13, 24, 611, DateTimeKind.Utc).AddTicks(3802),
                            UpdatedOn = new DateTime(2022, 1, 2, 7, 13, 24, 611, DateTimeKind.Utc).AddTicks(3802)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Go to the gym",
                            CreatedOn = new DateTime(2022, 1, 2, 7, 13, 24, 611, DateTimeKind.Utc).AddTicks(3802),
                            UpdatedOn = new DateTime(2022, 1, 2, 7, 13, 24, 611, DateTimeKind.Utc).AddTicks(3802)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Go to the grocery market",
                            CreatedOn = new DateTime(2022, 1, 2, 7, 13, 24, 611, DateTimeKind.Utc).AddTicks(3802),
                            UpdatedOn = new DateTime(2022, 1, 2, 7, 13, 24, 611, DateTimeKind.Utc).AddTicks(3802)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
